### ISSUE TITLE
Storages with managed memory produce non-managed output in ufuncs 

### ISSUE THREAD

**Issue by gronerl** [GridTools/gt4py#142]

**Comment by mcgibbon** [comment]
What I posted in slack:

Getting an unexpected error converting a particular gt4py storage to a cupy array. I need to make a cupy view which I can modify, which directly modifies the GPUStorage. This normally works, but not in this example with nans:

```python
>>> s = gt4py.storage.empty("gtcuda", [0, 0], [3, 3], float, managed_memory=True)
>>> s
GPUStorage([[0., 0., 0.],
            [0., 0., 0.],
            [0., 0., 0.]])
>>> s = s * cupy.nan
>>> s
GPUStorage([[nan, nan, nan],
            [nan, nan, nan],
            [nan, nan, nan]])
>>> s[1, 1] = 1
>>> s
GPUStorage([[nan, nan, nan],
            [nan,  1., nan],
            [nan, nan, nan]])
>>> cupy.asarray(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mcgibbon/miniconda3/envs/fv3util/lib/python3.7/site-packages/cupy/creation/from_data.py", line 68, in asarray
    return core.array(a, dtype, False, order)
  File "cupy/core/core.pyx", line 1785, in cupy.core.core.array
  File "cupy/core/core.pyx", line 1813, in cupy.core.core.array
  File "cupy/core/core.pyx", line 2814, in cupy.core.core._convert_object_with_cuda_array_interface
  File "cupy/cuda/memory.pyx", line 130, in cupy.cuda.memory.UnownedMemory.__init__
  File "cupy/cuda/runtime.pyx", line 503, in cupy.cuda.runtime.pointerGetAttributes
  File "cupy/cuda/runtime.pyx", line 201, in cupy.cuda.runtime.check_status
cupy.cuda.runtime.CUDARuntimeError: cudaErrorInvalidValue: invalid argument
```

The same error occurs if I use `data.gpu_view()` instead of `cupy.asarray`.

**Comment by gronerl** [comment]
As a work around,
instead of `s = s * cupy.nan`
`cupy.multiply(s, cupy.nan, out=s)` should work (or also out pointing to some other gpu/managed

**Comment by mbianco** [comment]
My understanding is that we are taking a different approach for the ufuncs now. Is this issue still relevant @gronerl @egparedes ?

**Comment by havogt** [comment]
obsolete
