### ISSUE TITLE
Slices of gt4py storages cannot be copied

### ISSUE THREAD

**Issue by mcgibbon** [GridTools/gt4py#31]
I have a piece of code which extracts variables (kind of like tracer variables) out of a larger array. After this, I needed to copy the array, and ran into this issue (shown as a MCVE):

```python
>>> arr = gt4py.storage.empty("numpy", default_origin=[0, 0, 0], shape=[10, 10, 10], dtype=float)
>>> s = arr[:, :, 0]
>>> copy.deepcopy(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/usr/src/gt4py/src/gt4py/storage/storage.py", line 350, in __deepcopy__
    res = super().__deepcopy__(memo=memo)
  File "/usr/src/gt4py/src/gt4py/storage/storage.py", line 186, in __deepcopy__
    managed_memory=not isinstance(self, ExplicitlySyncedGPUStorage),
  File "/usr/src/gt4py/src/gt4py/storage/storage.py", line 38, in empty
    shape=shape, dtype=dtype, backend=backend, default_origin=default_origin, mask=mask
  File "/usr/src/gt4py/src/gt4py/storage/storage.py", line 141, in __new__
    shape = storage_utils.normalize_shape(shape, mask)
  File "/usr/src/gt4py/src/gt4py/storage/utils.py", line 49, in normalize_shape
    "len(shape) must be equal to len(mask) or the number of 'True' entries in mask."
ValueError: len(shape) must be equal to len(mask) or the number of 'True' entries in mask.
```

I may find a way to work around the issue, but copy.deepcopy should probably work when used on slices?

**Comment by egparedes** [comment]
Related to (and probably fixed by): #28 #29

**Comment by jdahm** [comment]
This triggers an interesting new error:
```python
>>> s = arr[:, :, 0]
>>> copy.deepcopy(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/4i5w9iv836cg6hgr02g6phds6br8nas0-python3-3.8.9/lib/python3.8/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/Users/johannd/gt4py/src/gt4py/storage/storage.py", line 181, in __deepcopy__
    return self.copy()
  File "/Users/johannd/gt4py/src/gt4py/storage/storage.py", line 381, in copy
    res = super().copy()
  File "/Users/johannd/gt4py/src/gt4py/storage/storage.py", line 184, in copy
    res = empty(
  File "/Users/johannd/gt4py/src/gt4py/storage/storage.py", line 41, in empty
    return storage_t(
  File "/Users/johannd/gt4py/src/gt4py/storage/storage.py", line 136, in __new__
    default_origin, shape, dtype, mask = storage_utils.normalize_storage_spec(
  File "/Users/johannd/gt4py/src/gt4py/storage/utils.py", line 75, in normalize_storage_spec
    raise ValueError(
ValueError: Mask ((True, True, True)) and shape ((10, 10)) have non-matching sizes.len(shape)(=2) must be equal to len(mask)(=3) or the number of 'True' entries in mask '(True, True, True)'.
>>> type(s)
<class 'gt4py.storage.storage.CPUStorage'>
>>> s.mask
(True, True, True)
```

Taking a slice of a gt4py storage returns another storage, but the mask is not updated. This is a specific bug that could pretty easily be fixed.

**Comment by tehrengruber** [comment]
Taking a slice is prohibited now (#576) avoiding the issue altogether.
