### ISSUE TITLE
Functional:  Enable passing of non-empty offset providers

### ISSUE THREAD

**Issue by samkellerhals** [GridTools/gt4py#863]
When passing a non-empty field offset provider containing a `NeighborTableOffsetProvider` that is unused in a given stencil a `RuntimeError` is raised. We should be able to still compile this stencil even the offset is not used. See the example below.

```python
@field_operator
def stencil(a: Field[[CellDim, KDim], float]) -> Field[[CellDim, KDim], float]:
    return a


if __name__ == "__main__":
    mesh = SimpleMesh()

    a = random_field(mesh, CellDim, KDim)

    stencil(a, out=a, offset_provider={"C2E2CO": mesh.get_c2e2cO_offset_provider()})
``` 

```python
Traceback (most recent call last):
  File "/home/sk/.config/JetBrains/PyCharm2022.1/scratches/scratch_3.py", line 38, in <module>
    stencil(a, out=a, offset_provider={"C2E2CO": mesh.get_c2e2cO_offset_provider()})
  File "/home/sk/Dev/icon4py/_external_src/gt4py-functional/src/functional/ffront/decorator.py", line 543, in __call__
    return self.as_program()(*args, out, offset_provider=offset_provider, **kwargs)
  File "/home/sk/Dev/icon4py/_external_src/gt4py-functional/src/functional/ffront/decorator.py", line 314, in __call__
    backend(
  File "/home/sk/Dev/icon4py/_external_src/gt4py-functional/src/functional/iterator/processor_interface.py", line 57, in __call__
    self.executor_function(fencil, *args, **kwargs)
  File "/home/sk/Dev/icon4py/_external_src/gt4py-functional/src/functional/fencil_processors/roundtrip.py", line 147, in executor
    fencil(*args, **new_kwargs)
  File "/tmp/tmpn65941s2.py", line 16, in __field_operator_stencil_wrapper
  File "/home/sk/Dev/icon4py/_external_src/gt4py-functional/src/functional/iterator/runtime.py", line 72, in __call__
    fendef_embedded(self.function, *args, **kwargs)
  File "/home/sk/Dev/icon4py/_external_src/gt4py-functional/src/functional/iterator/embedded.py", line 1007, in fendef_embedded
    fun(*args)
  File "/tmp/tmpn65941s2.py", line 13, in __field_operator_stencil
  File "/home/sk/Dev/icon4py/_external_src/gt4py-functional/src/functional/iterator/dispatcher.py", line 18, in __call__
    return self.dispatcher._funs[self.dispatcher.key][self.fun.__name__](*args, **kwargs)
  File "/home/sk/Dev/icon4py/_external_src/gt4py-functional/src/functional/iterator/embedded.py", line 965, in closure
    _validate_domain(domain_, kwargs["offset_provider"])
  File "/home/sk/Dev/icon4py/_external_src/gt4py-functional/src/functional/iterator/embedded.py", line 949, in _validate_domain
    raise RuntimeError(
RuntimeError: Got a `CartesianDomain`, but found a `Connectivity` in `offset_provider`, expected `UnstructuredDomain`.
```

**Comment by havogt** [comment]
This is an inconsistency in how the grid_type is deduced: in fieldview we decide it's Cartesian because it doesn't use any unstructured offset. In execution we find a Connectivity and fail. We should check if the Connectivity is actually used.
