### ISSUE TITLE
Error message for non-existing backends

### ISSUE THREAD

**Issue by gronerl** [GridTools/gt4py#992]
When compiling a stencil with the `backend` parameter set to an invalid string value currently raises 
```
Traceback (most recent call last):
  File "/home/gronerl/gt4py/tmp.py", line 5, in <module>
    def test_stencil(out_storage: gtscript.Field[int]):
  File "/home/gronerl/gt4py/src/gt4py/gtscript.py", line 459, in _decorator
    StencilBuilder(
  File "/home/gronerl/gt4py/src/gt4py/stencil_builder.py", line 73, in __init__
    self.backend: "BackendType" = backend(self)
TypeError: 'NoneType' object is not callable

```
And should be a ValueError caught early on.

**Comment by jdahm** [comment]
I believe that https://github.com/GridTools/gt4py/pull/979 indirectly addresses this because it has to be type correct.
